### ISSUE TITLE
Can't seem to set order of tree

### ISSUE THREAD

**Issue by yankee14** [ysangkok/js-clrs-btree#5]
Hi, thank you for this great tool!

I am trying to set the order of the tree using the M entry on the right. It does not seem to work for me. Even the default init functions don't seem to obey the order setting.

Steps to reproduce:

1. Set M to 3 on the right under `Init insex`
2. Press `Init insex`
3. A tree is generated which violates M = 3.
4. Adding additional entries also ignores the M setting.

I am using the version found here: https://ysangkok.github.io/js-clrs-btree/btree.html

**Comment by yankee14** [comment]
When debugging, I see this line:

![image](https://user-images.githubusercontent.com/12487802/86025809-46d8e600-b9f4-11ea-9091-004480496153.png)

I guess that confused me, I assumed M was the order, and the max number of keys would just be `M - 1`. It only supports odd numbers of keys?

**Comment by ysangkok** [comment]
Yeah, I believe it only supports an odd number of keys. The definition is from CLRS, but I don't have the book anymore, and I don't remember the reasoning. If you have any suggestions for making it more clear, I'd be happy to hear them. But there are lot of things that could be improved, I guess...

**Comment by yankee14** [comment]
@ysangkok oh no worries! I appreciate the tool, I was able to use it enough to create nice looking trees for a paper I was writing. I might make a pull request some day.

Thanks
